services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    restart: unless-stopped

  frontend-user:
    build:
      context: ./frontend-user
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped
