import { QRCodeSVG } from 'qrcode.react'

const comingSoon = (name: string, cb?: (msg: string) => void) => (e: React.MouseEvent) => {
  e.preventDefault()
  cb?.('「' + name + '」模块正在建设中，敬请期待')
}

export function Header({ onToast }: { onToast?: (msg: string) => void }) { return (<header className="site-header">
  <div className="header-top"><div className="container header-top-inner"><span className="header-slogan">同程旅行 — 让旅行更简单</span><div className="header-top-right"><a href="#login" className="header-link" onClick={comingSoon('登录', onToast)}>登录</a><span className="header-sep">|</span><a href="#register" className="header-link" onClick={comingSoon('注册', onToast)}>注册</a><span className="header-sep">|</span><a href="#service" className="header-link" onClick={comingSoon('客户服务', onToast)}>客户服务</a><span className="header-sep">|</span><a href="#app" className="header-link" onClick={comingSoon('手机APP', onToast)}>手机APP</a></div></div></div>
  <div className="header-nav"><div className="container header-nav-inner"><div className="header-logo"><svg width="34" height="34" viewBox="0 0 34 34" fill="none"><rect width="34" height="34" rx="9" fill="#00b894" /><text x="6" y="23" fill="#fff" fontSize="15" fontWeight="bold">TC</text></svg><span className="logo-text">同程旅行</span></div><nav className="main-nav"><a href="#hotel" className="nav-item" onClick={comingSoon('酒店', onToast)}>酒店</a><a href="#flight" className="nav-item nav-active">机票</a><a href="#train" className="nav-item" onClick={comingSoon('火车票', onToast)}>火车票</a><a href="#car" className="nav-item" onClick={comingSoon('汽车票', onToast)}>汽车票</a><a href="#tour" className="nav-item" onClick={comingSoon('旅游', onToast)}>旅游</a><a href="#attraction" className="nav-item" onClick={comingSoon('景点门票', onToast)}>景点门票</a></nav></div></div>
  <div className="header-sub-nav"><div className="container header-sub-inner"><a href="#domestic" className="sub-nav-item" onClick={comingSoon('国内机票', onToast)}>国内机票</a><a href="#international" className="sub-nav-item sub-nav-active">国际·港澳机票</a><a href="#special" className="sub-nav-item" onClick={comingSoon('特价机票', onToast)}>特价机票</a><a href="#checkin" className="sub-nav-item" onClick={comingSoon('航班动态', onToast)}>航班动态</a></div></div>
</header>) }

export function Footer({ onToast }: { onToast?: (msg: string) => void }) { return (<footer className="site-footer"><div className="container footer-inner"><div className="footer-columns">
  <div className="footer-col"><h4 className="footer-col-title">关于同程</h4><a href="#about" className="footer-link" onClick={comingSoon('关于我们', onToast)}>关于我们</a><a href="#contact" className="footer-link" onClick={comingSoon('联系我们', onToast)}>联系我们</a><a href="#join" className="footer-link" onClick={comingSoon('加入我们', onToast)}>加入我们</a><a href="#news" className="footer-link" onClick={comingSoon('新闻中心', onToast)}>新闻中心</a></div>
  <div className="footer-col"><h4 className="footer-col-title">帮助中心</h4><a href="#faq" className="footer-link" onClick={comingSoon('常见问题', onToast)}>常见问题</a><a href="#refund" className="footer-link" onClick={comingSoon('退改签政策', onToast)}>退改签政策</a><a href="#insurance" className="footer-link" onClick={comingSoon('保险服务', onToast)}>保险服务</a><a href="#feedback" className="footer-link" onClick={comingSoon('意见反馈', onToast)}>意见反馈</a></div>
  <div className="footer-col"><h4 className="footer-col-title">合作伙伴</h4><a href="#airline" className="footer-link" onClick={comingSoon('航空公司', onToast)}>航空公司</a><a href="#hotel-partner" className="footer-link" onClick={comingSoon('酒店合作', onToast)}>酒店合作</a><a href="#ad" className="footer-link" onClick={comingSoon('广告合作', onToast)}>广告合作</a><a href="#affiliate" className="footer-link" onClick={comingSoon('分销联盟', onToast)}>分销联盟</a></div>
  <div className="footer-col"><h4 className="footer-col-title">关注我们</h4><a href="#wechat" className="footer-link" onClick={comingSoon('微信公众号', onToast)}>微信公众号</a><a href="#weibo" className="footer-link" onClick={comingSoon('官方微博', onToast)}>官方微博</a><a href="#tiktok" className="footer-link" onClick={comingSoon('抖音号', onToast)}>抖音号</a></div>
  <div className="footer-col footer-col-qr"><h4 className="footer-col-title">下载APP</h4><div className="qr-placeholder"><QRCodeSVG value="https://www.ly.com/app" size={80} bgColor="transparent" fgColor="#adb5bd" level="M" /><span className="qr-text">扫码下载APP</span></div></div>
</div><div className="footer-bottom"><p>© 2024 同程旅行 版权所有 | 苏ICP备XXXXXXXX号 | 增值电信业务经营许可证</p><p className="footer-disclaimer">航班信息由各航空公司实时提供，价格与余票以实际支付时为准。</p></div></div></footer>) }
